# https://taskfile.dev

version: '3'

vars:
  CLUSTER_NAME: "kind-cluster"
  APP_NAMESPACE: "apps"

includes:
  cluster:
    taskfile: kind/Taskfile.yml
    dir: kind
    internal: true
  
  monitoring:
    taskfile: monitoring/Taskfile.yml
    dir : monitoring
    internal: true
  
  istio:
    taskfile: istio/Taskfile.yml
    dir: istio
    internal: true
  
  apps:
    taskfile: app/k8s/Taskfile.yml
    dir: app/k8s
    internal: true

tasks:
  create-gateways:
    desc: Create Gateways
    internal: true
    cmds:
      - task: monitoring:create-gateways
      - task: istio:create-gateways

  messages:
    desc: Show the messages
    internal: true
    silent: true
    vars:
      APPS: app-a kiali grafana 
    cmds:
      - for: { var: APPS }
        cmd: echo -e "\n \n add 1270.0.0.1 {{.ITEM}}.local to /etc/hosts"

  create:
    desc: Create a kind cluster
    cmds:
      - task: cluster:create-kind-cluster
      - task: monitoring:install-monitoring
      - task: istio:create-istio
      - task: create-gateways
      - task: apps:deployApps
      - task: messages
  
  client-logs:
    desc: Show the client logs
    cmds:
      - kubectl -n {{.APP_NAMESPACE}} logs -l app=app-a -c app-a -f 
  
  clean:
    desc: Delete the kind cluster
    cmds:
      - task: cluster:clean

      
    
