# https://taskfile.dev

version: '3'

vars:
  CLUSTER_NAME: "cluster"
  APP_NAMESPACE: "apps"

includes:
  cluster:
    taskfile: kind/Taskfile.yml
    dir: kind
    internal: true
  
  monitoring:
    taskfile: monitoring/Taskfile.yml
    dir : monitoring
    internal: true
  
  istio:
    taskfile: istio/Taskfile.yml
    dir: istio
    internal: true
  
  apps:
    taskfile: app/k8s/Taskfile.yml
    dir: app/k8s
    internal: true
  
  k6:
    taskfile: k6/Taskfile.yml
    dir: k6
    internal: true

tasks:
  check-tools:
    desc: "Check if Docker, Kind, and Helm are installed"
    preconditions:
      - sh: command -v docker
        msg: "Docker is not installed. Please install Docker to proceed."
      - sh: command -v kind
        msg: "Kind is not installed. Please install Kind to proceed."
      - sh: command -v helm
        msg: "Helm is not installed. Please install Helm to proceed."
    cmds:
      - echo "All required tools (Docker, Kind, Helm) are installed."
    
  create-gateways:
    desc: Create Gateways
    internal: true
    cmds:
      - task: monitoring:create-gateways
      - task: istio:create-gateways

  messages:
    desc: Show the messages
    internal: true
    silent: true
    vars:
      APPS: proxy kiali grafana 
    cmds:
      - for: { var: APPS }
        cmd: echo -e "\n \n add 127.0.0.1 {{.ITEM}}.local to /etc/hosts"

  create:
    desc: Create a kind cluster
    deps:
      - check-tools
    cmds:
      - task: cluster:create-kind-cluster
      - task: monitoring:install-monitoring
      - task: istio:create-istio
      - task: create-gateways
      - task: apps:deployApps
      - task: k6:deploy-k6-operator
      - task: messages
  
  client-logs:
    desc: Show the client logs
    cmds:
      - kubectl -n {{.APP_NAMESPACE}} logs -l app=app-a -c app-a -f 
  
  clean:
    desc: Delete the kind cluster
    cmds:
      - task: cluster:clean

      
    
