apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - Rbac
  - gateway.yaml

configMapGenerator:
- envs:
  - configmap.env
  name: proxy-to-all-cm


images:
  - name: change:image
    newName: isarn/istio_lab_proxytoall
    newTag: latest

patches:
- path: patches/deployment-sa-patch.yaml
  target:
      kind: Deployment
      name: app-placeholder
- path: patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: app-placeholder
- path: patches/hpa-patch.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: app-placeholder-hpa
- path: patches/service-patch.yaml
  target:
    kind: Service
    name: app-placeholder-service
