apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base


configMapGenerator:
- envs:
  - configmap.env
  name: app-b-cm


images:
  - name: change:image
    newName: isarn/istio_lab_appb
    newTag: latest

patches:
- path: patches/deployment-patch.yaml
  target:
    kind: Deployment
    name: app-placeholder
- path: patches/hpa-patch.yaml
  target:
    kind: HorizontalPodAutoscaler
    name: app-placeholder-hpa
- path: patches/service-patch.yaml
  target:
    kind: Service
    name: app-placeholder-service
