apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-b-destination-rule
spec:
  host: app-b
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 5
# ---
# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: app-b-virtual-service
# spec:
#   hosts:
#     - app-b
#   http:
#     - timeout: 10s
#       route:
#         - destination:
#             host: app-b
