apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: app-b-destination-rule
spec:
  host: app-b
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 10
      http:
        http1MaxPendingRequests: 5
