apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: app-b-sidecar
spec:
  workloadSelector:
    labels:
      app: app-b
  inboundConnectionPool:
    tcp:
      maxConnections: 10
    http:
      http1MaxPendingRequests: 5