{
 "title": "Istio",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sourceApp",
    "label": "sourceApp",
    "query": {
     "query": "label_values(istio_requests_total,app)"
    }
   },
   { "name": "interval", "label": "interval", "query": "2m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Rate limited apps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_flags=\"UO\"}[$interval])) by (app, destination_service_name)\n/\nsum(rate(istio_requests_total[$interval])) by (app, destination_service_name)",
     "legendFormat": "{{app}} rate limited to {{destination_service_name}} present"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{app=\"${sourceApp}\"}[${interval}])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (app) (\n  rate(\n    istio_requests_total{\n      reporter=~\"source\",\n      response_code!~\"5.*\",\n      app=\"${sourceApp}\"\n    }[$interval]\n  )\n)\n/\nsum by (app) (\n  rate(\n    istio_requests_total{\n      reporter=~\"source\",\n      app=\"${sourceApp}\"\n    }[$interval]\n  )\n)\n",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, app) (\n    rate(\n      istio_request_duration_milliseconds_bucket{\n          reporter=~\"source\",\n          app=~\"${sourceApp}\",\n      }\n    [$interval])\n  )\n)",
     "legendFormat": "{{app}} - 50%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, app) (\n    rate(\n      istio_request_duration_milliseconds_bucket{\n          reporter=~\"source\",\n          app=~\"${sourceApp}\",\n      }\n    [$interval])\n  )\n)",
     "legendFormat": "{{app}} - 90%"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, app) (\n    rate(\n      istio_request_duration_milliseconds_bucket{\n          reporter=~\"source\",\n          app=~\"${sourceApp}\",\n      }\n    [$interval])\n  )\n)",
     "legendFormat": "{{app}} - 99%"
    }
   ]
  },
  {
   "title": "Envoy connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg(envoy_server_total_connections{app=~\"${sourceApp}\"})",
     "legendFormat": "connections"
    }
   ]
  }
 ]
}