{
 "title": "RED-Istio",
 "description": "RED for istio",
 "tags": [ "red-grafonnet" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_status_phase, namespace)"
   },
   {
    "name": "sourceApp",
    "query": "label_values(istio_requests_total{namespace=\"$namespace\"}, app)"
   },
   {
    "name": "interval",
    "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate Limited Apps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{response_flags=~\"UO|URX\",reporter=\"source\"}[$interval])) by (app,destination_app)\n/\nsum(rate(istio_requests_total{reporter=\"source\"}[$interval])) by (app,destination_app)\n",
     "legendFormat": "{{source_app}} rate limited to {{destination_app}} %"
    }
   ]
  },
  {
   "title": "Envoy Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg(envoy_server_total_connections{app=~\"${sourceApp}\"})\n",
     "legendFormat": "connections"
    }
   ]
  },
  { "title": "Incoming ${interval}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (destination_app)(\n    rate(istio_requests_total{\n        destination_app=\"${sourceApp}\",\n        reporter=\"source\"\n        }[${interval}]\n    )\n) \n",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (destination_app) (\n  rate(\n    istio_requests_total{\n      reporter=\"source\",\n      response_code!~\"5.*\",\n      destination_app=\"${sourceApp}\"\n    }[$interval]\n  )\n  )\n  /\n  sum by (destination_app) (\n    rate(\n      istio_requests_total{\n        reporter=\"source\",\n        destination_app=\"${sourceApp}\"\n      }[$interval]\n    )\n  )\n",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, destination_app) (\n    rate(\n      istio_request_duration_milliseconds_bucket{\n          reporter=~\"source\",\n          destination_app=\"${sourceApp}\",\n      }\n    [$interval])\n  )\n)\n",
     "legendFormat": "{{destination_app}} - 50%\n"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, destination_app) (\n    rate(\n      istio_request_duration_milliseconds_bucket{\n          reporter=~\"source\",\n          destination_app=\"${sourceApp}\",\n      }\n    [$interval])\n  )\n)\n",
     "legendFormat": "{{destination_app}} - 90%\n"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, destination_app) (\n    rate(\n      istio_request_duration_milliseconds_bucket{\n          reporter=~\"source\",\n          destination_app=\"${sourceApp}\",\n      }\n    [$interval])\n  )\n)\n",
     "legendFormat": "{{destination_app}} - 99%\n"
    }
   ]
  },
  { "title": "Outgoing ${interval}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (destination_app)(\n    rate(istio_requests_total{\n        source_app=\"${sourceApp}\",\n        reporter=\"source\"\n        }[${interval}]\n    )\n) \n",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (destination_app) (\n  rate(\n    istio_requests_total{\n      reporter=\"source\",\n      response_code!~\"5.*\",\n      source_app=\"${sourceApp}\"\n    }[$interval]\n  )\n  )\n  /\n  sum by (destination_app) (\n    rate(\n      istio_requests_total{\n        reporter=\"source\",\n        source_app=\"${sourceApp}\"\n      }[$interval]\n    )\n  )\n",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, source_app) (\n    rate(\n      istio_request_duration_milliseconds_bucket{\n          reporter=~\"source\",\n          source_app=\"${sourceApp}\",\n      }\n    [$interval])\n  )\n)\n",
     "legendFormat": "{{destination_app}} - 50%\n"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, source_app) (\n    rate(\n      istio_request_duration_milliseconds_bucket{\n          reporter=~\"source\",\n          source_app=\"${sourceApp}\",\n      }\n    [$interval])\n  )\n)\n",
     "legendFormat": "{{destination_app}} - 90%\n"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, source_app) (\n    rate(\n      istio_request_duration_milliseconds_bucket{\n          reporter=~\"source\",\n          source_app=\"${sourceApp}\",\n      }\n    [$interval])\n  )\n)\n",
     "legendFormat": "{{destination_app}} - 99%\n"
    }
   ]
  }
 ]
}