version: '3'

vars:
  DOCKER_USERNAME: isarn
  DOCKER_REPO_PREFIX: istio_lab

tasks:
  buildApps:
    desc: Build the apps
    vars:
      APPS: proxyToAll appA appB appC
    cmds:
      - for: { var: APPS }
        cmd: |
          repo=$(echo "{{.DOCKER_USERNAME}}/{{.DOCKER_REPO_PREFIX}}_{{.ITEM}}" | tr '[:upper:]' '[:lower:]')
          docker build --build-arg APP_DIR={{.ITEM}} --build-arg PORT=8080 -t $repo:latest .
  
  pushApps:
    desc: Push the apps to Docker Hub
    vars:
      APPS: proxyToAll appA appB appC
    deps:
      - buildApps
    cmds:
      - for: { var: APPS }
        cmd: |
          repo=$(echo "{{.DOCKER_USERNAME}}/{{.DOCKER_REPO_PREFIX}}_{{.ITEM}}" | tr '[:upper:]' '[:lower:]')
          docker push $repo:latest
  
  pushAppsMultiArch:
    desc: Push the apps to Docker Hub
    vars:
      APPS: proxyToAll appA appB appC
    cmds:
      - for: { var: APPS }
        cmd: |
          repo=$(echo "{{.DOCKER_USERNAME}}/{{.DOCKER_REPO_PREFIX}}_{{.ITEM}}" | tr '[:upper:]' '[:lower:]')
          docker buildx create --name multy-arch --use || docker buildx use multy-arch
          docker buildx build --build-arg APP_DIR={{.ITEM}} --build-arg PORT=8080 --platform linux/amd64,linux/arm64 -t $repo:latest --push .
  
  deleteImagesForcefully:
    desc: Delete all images forcefully
    cmds:
      - docker images | grep '^{{.DOCKER_USERNAME}}/{{.DOCKER_REPO_PREFIX}}_' | awk '{print $3}' | xargs docker rmi --force

