version: '3'

shopt: [globstar]

tasks:
  init:
    desc: "Initialize the project"
    cmds:
      - jb install github.com/grafana/grafonnet/gen/grafonnet-latest@main

  generate:
    desc: "Generate the dashboards"
    preconditions:
      - sh: test -d vendor 
        msg: "Please run `task init` first"
    deps:
      - format
    cmds:
      - jsonnet -J vendor -m ../dashboards -e '(import "main.libsonnet")'
  
  format:
    desc: "Format the jsonnet files"
    cmds:
      - jsonnetfmt -i **/*.libsonnet
